site_name: aiselectors
repo_url: https://github.com/DallanQ/aiselectors
site_url: https://DallanQ.github.io/aiselectors
site_description: BeautifulSoup extended with prompts to extract data and calls to Playwright to make it fast to write reliable web agents.
site_author: Dallan Quass
edit_uri: edit/main/docs/
repo_name: DallanQ/aiselectors
copyright: Maintained by <a href="https://DallanQ.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DallanQ/aiselectors
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/aiselectors

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
